config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :pages, only: [ :show ], param: :permalink

  get "cart",  to: "cart#show"
  post "cart/add"
  post "cart/remove"

  resources :cart, only: %i[create destroy]

  root to: "products#index"

  resources :products do
    collection do
      get :search
    end
  end

  resources :categories, only: [ :index, :show ]
  resources :products, only: [ :index, :show ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    authorizable_ransackable_attributes
  end

  def self.ransackable_associations(auth_object = nil)
    authorizable_ransackable_associations
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :orders
  has_many :products, through: :orders

  def total
    orders.to_a.sum { |order| order.total }
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  def total
    product.price * quantity
  end
end

app/models/page.rb
class Page < ApplicationRecord
  validates :title, :content, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/product.rb
require "image_processing/mini_magick"

class Product < ApplicationRecord
  belongs_to :category

  has_many :orders
  has_many :carts, through: :orders

  has_one_attached :image

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :stock_quantity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :set_render_cart
  before_action :initialize_cart

  def set_render_cart
    @render_cart = true
  end

  def initialize_cart
    @cart ||= Cart.find_by(id: session[:cart_id])

    if @cart.nil?
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def show
    @render_cart = false
  end

  def add
    @product = Product.find_by(id: params[:id])
    quantity = params[:quantity].to_i
    current_order = @cart.orders.find_by(product_id: @product.id)
    if current_order && quantity > 0
      current_order.update(quantity:)
    elsif quantity <= 0
      current_order.destroy
    else
      @cart.orders.create(product: @product, quantity:)
      flash[:notice] = "Added to the cart"
    end

    redirect_to root_path
  end

  def remove
    Order.find_by(id: params[:id]).destroy

    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(:name)
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products.page(params[:page])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
    @page = Page.find_by(permalink: params[:permalink])

    if @page.nil?
      render file: Rails.root.join("public", "404.html"), status: :not_found
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.order(:name).page(params[:page]).per(12)
  end

  def show
    @product = Product.find(params[:id])
  end

  def search
    @categories = Category.all
    @query = params[:query]
    @category_id = params[:category_id]

    @products = Product.all

    if @query.present?
      @products = @products.where("LOWER(name) LIKE ? OR LOWER(description) LIKE ?", "%#{@query.downcase}%", "%#{@query.downcase}%")
    end

    @products = @products.where(category_id: @category_id) if @category_id.present?

    @products = @products.page(params[:page]).per(12)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breadcrumbs_helper.rb
module BreadcrumbsHelper
  def breadcrumbs
    crumbs = []

    if controller_name == "categories"
      if action_name == "index"
        # Categories Index Page
        crumbs << link_to("Home", root_path)
        crumbs << "Categories"
      elsif action_name == "show"
        # Category Show Page
        crumbs << link_to("Home", root_path)
        crumbs << link_to("Categories", categories_path)
        crumbs << @category.name
      end
    elsif controller_name == "products" && action_name == "show"
      # Product Show Page
      crumbs << link_to("Home", root_path)
      crumbs << link_to("Categories", categories_path)
      crumbs << link_to(@product.category.name, category_path(@product.category)) if @product.category
      crumbs << @product.name
    elsif controller_name == "cart"
      if action_name == "show"
        crumbs << link_to("Home", root_path)
        crumbs << link_to("Cart", cart_path)
      end
    else
      # Default (e.g., Home Page)
      crumbs << link_to("Home", root_path)
    end

    crumbs.join(" >> ").html_safe
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/cart/_cart.html.erb
    <% if @cart.orders.count > 0 %>
        <h1>Cart</h1>
        <%= render "cart/orders" %>
    <% else %>
        <p>Your cart is empty.</p>
    <% end %>

app/views/cart/_orders.html.erb
<% @cart.orders.each do |order| %>
    <% product = order.product %>
      <p>Name: <%= product.name %></h3>
      <p>Price: <%= number_to_currency product.price / 100.0 %></p>
      
      <%= form_with(url: cart_add_path) do |f| %>
        <%= f.hidden_field :id, value: product.id %>
        <%= f.number_field :quantity, value: order.quantity, min: 0 %>
        <%= f.submit "Add to Cart" %>
      <% end %>
      
      <%= form_with(url: cart_remove_path) do |f| %>
        <%= f.hidden_field :id, value: order.id %>
        <%= f.submit "X" %>
      <% end %>
      
      <strong>Total:</strong><%= number_to_currency(order.total / 100) %>
      <br>
      <br>
<% end %>

app/views/cart/show.html.erb
<%= render "cart/orders" %>

app/views/categories/_category.html.erb
<p><strong><%= link_to category.name, category %></strong></p>

app/views/categories/index.html.erb
<h1>All Categories</h1>

<section>
  <%= render @categories %>
</section>

app/views/categories/show.html.erb
<h1><%= @category.name %> Products</h1>

<aside>
  <% if @products.any? %>
    <div>
      <% @products.each do |product| %>
      <div>
        <p><strong><%= link_to product.name, product %></strong></p>
      <% end %>
    </div>
    <%= paginate @products %>
  <% else %>
    <p>No products found in this category.</p>
  <% end %>
</aside>

<%= link_to "Back to All Categories", categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Wpgsneaker Ecommerce" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <link rel="stylesheet" href="https://unpkg.com/mvp.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main>
      <%= render partial: "cart/cart" if @render_cart %>

      <% if flash[:notice] %>
        <h3><%= flash[:notice] %></h3>
      <% end %>
      
      <%= breadcrumbs %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/show.html.erb
<h1><%= @page.title %></h1>
<div class="page-content">
  <%= @page.content.html_safe %>
</div>

app/views/products/_product.html.erb
<aside>
  <% if product.image.attached? %>
    <%= image_tag product.image %>
  <% else %>
    <%= image_tag asset_path('no_image.jpg'), size: "240x300"  %>
  <% end %>
  <h3><%= link_to product.name, product %></h3>
  <p>Price: <%= number_to_currency product.price / 100.0 %></p>
  <p><%= product.description %></p>

  <%= form_with(url: cart_add_path) do |f| %>
    <%= f.hidden_field :id, value: product.id %>
    <%= f.number_field :quantity, value: 0, min: 1 %>
    <%= f.submit "Add to Cart" %>
  <% end %>
</aside>

app/views/products/index.html.erb
<h1>Products</h1>

<section>
  <%= render @products %>
</section>

<%= paginate @products %>

app/views/products/search.html.erb
<h1>Search Products</h1>

<section>
  <%= form_with url: search_products_path, method: :get, local: true do %>
    <div>
      <%= label_tag :query, "Search by keyword:" %>
      <%= text_field_tag :query, params[:query], placeholder: "Enter keyword" %>
    </div>

    <div>
      <%= label_tag :category_id, "Filter by category:" %>
      <%= select_tag :category_id, options_from_collection_for_select(@categories, :id, :name, params[:category_id]), include_blank: "All Categories" %>
    </div>

    <%= submit_tag "Search" %>
  <% end %>
</section>

<h2>Search Results</h2>

<section>
  <%= render @products %>
</section>

<div>
  <%= paginate @products %>
</div>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<%= link_to "Back to All Products", products_path %>

<section>
  <%= render @product %>
<section>